### PR TITLE
Ember cli 3 5

### LINKED ISSUE #4: Upgrade ember-cli
Ran into this issue: https://github.com/ember-cli/ember-cli/issues/6513, am on new for me MacBook Pro with touchbar.

I have a branch for this, in which just bumped ember-cli so that I could run it locally. (Ironically, I have an unrelated problem, where I logged into GitHub for a friend and now can't push to my own fork. To be debugged another time...) 

Maybe the ember-cli upgrade doesn't work because copying the contributors doesn't include the GitHub profile links? See gif:

emberland

### PR DESCRIPTION
**Pull request by tylerturdenpants**
Updates ember and friends, addresses contributor copy problem in issue #4 by setting the raw HTML in the document

Closes #4

### CODE REVIEW

File: app/controllers/index.js [hunk 1]
```diff
@@ -50,11 +50,10 @@ stillLoading: not('isFinishedLoading'),
 
       const links = names.map((contrib) => {
         const contributor = escapeExpression(contrib).trim();
-        const link = `<a href="https://github.com/${contributor}" target="gh-user">@${contributor}</a>`;
-        return htmlSafe(link);
+        return `<a href="https://github.com/${contributor}" target="gh-user">@${contributor}</a>`;
       }).join(', ');
       document.querySelector('.fetch-contributors').click();
-      this.set('conListUniq', htmlSafe(links));
+      this.set('conListUniq', links);
```
Comment (jessica-jordan) [inline app/controllers/index.js]: :pray:
